[build]
  command = "# no build command"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 